### ISSUE TITLE
Git history was rewritten

### ISSUE THREAD

**Issue by tarsius** [bepvte/gtk-variant.el#3]
It appears that you have unintentionally rewritten history. You can fix that using:

```
git reset --hard fa0609b93f1ece777c0593529870390f21f5a788
git push --force origin master:master
```

**Comment by bepvte** [comment]
It was intentional, I was changing a name and email I no longer use

**Comment by tarsius** [comment]
I didn't notice that.

You might want to recreate `v1.0.0`, it still points at the old history.
