### ISSUE TITLE
`gtk-variant-set-frame` have no effect.

### ISSUE THREAD

**Issue by CyberFox001** [bepvte/gtk-variant.el#4]
When I run the Emacs command `gtk-variant-set-frame` and select dark, the window titlebar color is still light.

I use the latest version of gtk-variant.el and Emacs 28.2.

**Comment by bepvte** [comment]
It won't work when using the wayland backend for emacs. I don't use emacs in a GTK environment very often anymore and don't plan on fixing this for wayland.
